In [ ]:
import tensorflow_hub as hub
import tensorflow as tf
print(tf.__version__)
print(hub.__version__)

2.11.0
0.12.0


In [ ]:
import pandas as pd
data=pd.read_csv('/content/clean_data.csv')

del data['Unnamed: 0']
print(data.head())


                                              review sentiment
0  One reviewer mentioned after watching Oz episo...  positive
1  A wonderful little production The filming tech...  positive
2  I thought wonderful way spend time hot summer ...  positive
3  Basically s family little boy Jake think s zom...  negative
4  Petter Mattei Love Time Money visually stunnin...  positive


In [ ]:
train=data.review[:100]
test=data.review[100:150]


In [ ]:
elmo = hub.load("https://tfhub.dev/google/elmo/2").signatures["default"]

In [ ]:
def word_embedding_elmo(input_text):
  return elmo(tf.reshape(tf.cast(input_text, tf.string), [-1]))["elmo"]

cv_train=train.apply(word_embedding_elmo)

In [ ]:
print(cv_train.shape)

(100,)


In [ ]:
print(type(cv_train))

<class 'pandas.core.series.Series'>


In [ ]:
import numpy as np
print(np.asarray(cv_train))

[<tf.Tensor: shape=(1, 217, 1024), dtype=float32, numpy=
 array([[[ 0.08764993, -0.39284247, -0.12913212, ..., -0.50598675,
          -0.08334018, -0.24802226],
         [-1.4074332 , -1.0422509 , -0.04297161, ...,  0.72488654,
           0.16444784,  0.32420522],
         [-0.34171382,  0.25839734, -0.37466776, ...,  0.21067663,
           0.13710299,  0.17462157],
         ...,
         [-0.26514864, -0.21866705, -0.36755934, ...,  0.10037643,
           0.01692116, -0.2969537 ],
         [ 0.64306784, -0.21654095, -0.46210235, ..., -0.40489915,
          -0.13170537,  0.12243146],
         [ 0.31259534,  0.05755736,  0.19264239, ..., -0.05602356,
           0.4559303 ,  0.40685296]]], dtype=float32)>
 <tf.Tensor: shape=(1, 114, 1024), dtype=float32, numpy=
 array([[[ 0.29287   , -0.14377989, -0.32574046, ..., -0.45445156,
          -0.18946093, -0.15084939],
         [-0.1485458 , -0.51634777,  0.17114702, ..., -0.03330457,
           0.33182615,  0.15612526],
         [-0.09244186,

In [ ]:
#print(sentiment)
y_train=data.sentiment[:100]
y_test=data.sentiment[100:150]

def sentiment(text):
  if text=="positive":
    return 1
  else: 
    return 0
y_train=y_train.apply(sentiment)
print(y_train)

0     1
1     1
2     1
3     0
4     1
     ..
95    1
96    0
97    0
98    0
99    1
Name: sentiment, Length: 100, dtype: int64


In [ ]:
y_train = tf.keras.utils.to_categorical(y_train)
print(y_train)

[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]


In [ ]:
print(y_train)

[[[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[0. 1.]
  [1. 0.]]

 [[0. 1.]
  [1. 0.]]

 [[1. 0.]
  [0. 1.]]

 [[1. 0.]


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

clf= DecisionTreeClassifier()

clf = clf.fit(np.asarray(cv_train),np.asarray(y_train))

#y_pred = clf.predict(cv_test)

ValueError: ignored

In [ ]:
#print("Accuracy_DT:",metrics.accuracy_score(y_test, y_pred))