## Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
!pip install tensorflow

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [ ]:
### Vocabulary size
voc_size=500

## One Hot Representation

In [ ]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[29, 357, 350, 87], [29, 357, 350, 437], [29, 11, 350, 352], [341, 6, 468, 142, 257], [341, 6, 468, 142, 214], [185, 29, 219, 350, 340], [165, 214, 482, 142]]


## Word Embedding Represntation

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  29 357 350  87]
 [  0   0   0   0  29 357 350 437]
 [  0   0   0   0  29  11 350 352]
 [  0   0   0 341   6 468 142 257]
 [  0   0   0 341   6 468 142 214]
 [  0   0   0 185  29 219 350 340]
 [  0   0   0   0 165 214 482 142]]


In [ ]:
## 10 feature dimesnions
dim=10

In [ ]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  29, 357, 350,  87], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])


1/1 [==============================] - 0s 144ms/step


array([[ 0.01747844,  0.03142833,  0.00123465,  0.04141033, -0.02504481,
        -0.04304005, -0.00121895,  0.01058253, -0.04424038, -0.03062264],
       [ 0.01747844,  0.03142833,  0.00123465,  0.04141033, -0.02504481,
        -0.04304005, -0.00121895,  0.01058253, -0.04424038, -0.03062264],
       [ 0.01747844,  0.03142833,  0.00123465,  0.04141033, -0.02504481,
        -0.04304005, -0.00121895,  0.01058253, -0.04424038, -0.03062264],
       [ 0.01747844,  0.03142833,  0.00123465,  0.04141033, -0.02504481,
        -0.04304005, -0.00121895,  0.01058253, -0.04424038, -0.03062264],
       [-0.02701455,  0.03170366,  0.03528719, -0.01858225,  0.04656846,
        -0.01284852,  0.0088511 ,  0.03033883,  0.01276756,  0.03498018],
       [ 0.02698244, -0.01309518, -0.00071635, -0.01854755,  0.01999242,
        -0.00243177,  0.03993643,  0.04456209,  0.0342336 ,  0.04442973],
       [ 0.00807639,  0.0230017 , -0.03097576,  0.0036391 ,  0.04894943,
         0.02264689, -0.04357005, -0.04495572

In [ ]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 45ms/step
[[[ 1.74784400e-02  3.14283259e-02  1.23465061e-03  4.14103307e-02
   -2.50448119e-02 -4.30400483e-02 -1.21895224e-03  1.05825290e-02
   -4.42403816e-02 -3.06226369e-02]
  [ 1.74784400e-02  3.14283259e-02  1.23465061e-03  4.14103307e-02
   -2.50448119e-02 -4.30400483e-02 -1.21895224e-03  1.05825290e-02
   -4.42403816e-02 -3.06226369e-02]
  [ 1.74784400e-02  3.14283259e-02  1.23465061e-03  4.14103307e-02
   -2.50448119e-02 -4.30400483e-02 -1.21895224e-03  1.05825290e-02
   -4.42403816e-02 -3.06226369e-02]
  [ 1.74784400e-02  3.14283259e-02  1.23465061e-03  4.14103307e-02
   -2.50448119e-02 -4.30400483e-02 -1.21895224e-03  1.05825290e-02
   -4.42403816e-02 -3.06226369e-02]
  [-2.70145535e-02  3.17036621e-02  3.52871902e-02 -1.85822472e-02
    4.65684570e-02 -1.28485188e-02  8.85109976e-03  3.03388275e-02
    1.27675571e-02  3.49801816e-02]
  [ 2.69824378e-02 -1.30951777e-02 -7.16350973e-04 -1.85475461e-02
    1.99924223e-02 -2.43177265e

In [ ]:
embedded_docs[0]

array([  0,   0,   0,   0,  29, 357, 350,  87], dtype=int32)

In [ ]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 23ms/step
[[ 0.01747844  0.03142833  0.00123465  0.04141033 -0.02504481 -0.04304005
  -0.00121895  0.01058253 -0.04424038 -0.03062264]
 [ 0.01747844  0.03142833  0.00123465  0.04141033 -0.02504481 -0.04304005
  -0.00121895  0.01058253 -0.04424038 -0.03062264]
 [ 0.01747844  0.03142833  0.00123465  0.04141033 -0.02504481 -0.04304005
  -0.00121895  0.01058253 -0.04424038 -0.03062264]
 [ 0.01747844  0.03142833  0.00123465  0.04141033 -0.02504481 -0.04304005
  -0.00121895  0.01058253 -0.04424038 -0.03062264]
 [-0.02701455  0.03170366  0.03528719 -0.01858225  0.04656846 -0.01284852
   0.0088511   0.03033883  0.01276756  0.03498018]
 [ 0.02698244 -0.01309518 -0.00071635 -0.01854755  0.01999242 -0.00243177
   0.03993643  0.04456209  0.0342336   0.04442973]
 [ 0.00807639  0.0230017  -0.03097576  0.0036391   0.04894943  0.02264689
  -0.04357005 -0.04495572 -0.00555979 -0.00471705]
 [-0.00138181  0.02136585  0.0049241   0.00385581 -0.01103996 -0.01945206

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')