### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 588.3/588.3 MB 2.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 439.2/439.2 KB 49.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 85.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 35.0 MB/s eta 0:00:00
  Attempting uninstall: flatbuffers
    Found existing installation: flatbuffers 1.12
    Uninstalling flatbuffers-1.12:
      Successfully uninstalled flatbuffers-1.12
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.9.0
    Uninstalling tensorflow-estimator-2.9.0:
      Successfully uninstalled tensorflow-estimator-2.9.0
  Attempting uninstall: keras
    Found existing installation: keras 2.9.0
    Uninstalling keras-2.9.0:
      Successfully uninstalled keras-2.9.0
  Attempting uninstall: tensorboard
    Found existing i

In [21]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[48, 305, 7, 382], [48, 305, 7, 46], [48, 121, 7, 55], [468, 423, 65, 338, 447], [468, 423, 65, 338, 187], [91, 48, 80, 7, 133], [314, 11, 467, 338]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  48 305   7 382]
 [  0   0   0   0  48 305   7  46]
 [  0   0   0   0  48 121   7  55]
 [  0   0   0 468 423  65 338 447]
 [  0   0   0 468 423  65 338 187]
 [  0   0   0  91  48  80   7 133]
 [  0   0   0   0 314  11 467 338]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0,  48, 305,   7, 382], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 66ms/step


array([[ 0.0336266 , -0.04420923,  0.03326279,  0.03675016,  0.04281775,
        -0.03820918,  0.04112494, -0.02698019,  0.03329041,  0.0103259 ],
       [ 0.0336266 , -0.04420923,  0.03326279,  0.03675016,  0.04281775,
        -0.03820918,  0.04112494, -0.02698019,  0.03329041,  0.0103259 ],
       [ 0.0336266 , -0.04420923,  0.03326279,  0.03675016,  0.04281775,
        -0.03820918,  0.04112494, -0.02698019,  0.03329041,  0.0103259 ],
       [ 0.0336266 , -0.04420923,  0.03326279,  0.03675016,  0.04281775,
        -0.03820918,  0.04112494, -0.02698019,  0.03329041,  0.0103259 ],
       [-0.00353304, -0.01372648,  0.02257428,  0.01239265, -0.00881692,
        -0.01084014, -0.01053008, -0.00415802,  0.04271582,  0.03706283],
       [-0.02342725,  0.01284632,  0.04433629,  0.04154154, -0.03725727,
         0.03113561, -0.02562627, -0.00958662, -0.03861871,  0.039754  ],
       [-0.01039786, -0.01145361,  0.00988414, -0.00345533,  0.04146865,
        -0.02847247, -0.02019556, -0.02300214

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 39ms/step
[[[ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775
   -0.03820918  0.04112494 -0.02698019  0.03329041  0.0103259 ]
  [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775
   -0.03820918  0.04112494 -0.02698019  0.03329041  0.0103259 ]
  [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775
   -0.03820918  0.04112494 -0.02698019  0.03329041  0.0103259 ]
  [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775
   -0.03820918  0.04112494 -0.02698019  0.03329041  0.0103259 ]
  [-0.00353304 -0.01372648  0.02257428  0.01239265 -0.00881692
   -0.01084014 -0.01053008 -0.00415802  0.04271582  0.03706283]
  [-0.02342725  0.01284632  0.04433629  0.04154154 -0.03725727
    0.03113561 -0.02562627 -0.00958662 -0.03861871  0.039754  ]
  [-0.01039786 -0.01145361  0.00988414 -0.00345533  0.04146865
   -0.02847247 -0.02019556 -0.02300214 -0.01165978 -0.01076185]
  [-0.00898023  0.03176056 -0.03102802  0.01840689 -0.02395

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0,  48, 305,   7, 382], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 20ms/step
[[ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775 -0.03820918
   0.04112494 -0.02698019  0.03329041  0.0103259 ]
 [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775 -0.03820918
   0.04112494 -0.02698019  0.03329041  0.0103259 ]
 [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775 -0.03820918
   0.04112494 -0.02698019  0.03329041  0.0103259 ]
 [ 0.0336266  -0.04420923  0.03326279  0.03675016  0.04281775 -0.03820918
   0.04112494 -0.02698019  0.03329041  0.0103259 ]
 [-0.00353304 -0.01372648  0.02257428  0.01239265 -0.00881692 -0.01084014
  -0.01053008 -0.00415802  0.04271582  0.03706283]
 [-0.02342725  0.01284632  0.04433629  0.04154154 -0.03725727  0.03113561
  -0.02562627 -0.00958662 -0.03861871  0.039754  ]
 [-0.01039786 -0.01145361  0.00988414 -0.00345533  0.04146865 -0.02847247
  -0.02019556 -0.02300214 -0.01165978 -0.01076185]
 [-0.00898023  0.03176056 -0.03102802  0.01840689 -0.02395584 -0.012052
 

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]